---
kind: Namespace
apiVersion: v1
metadata:
  name: dasetnik
  labels:
    name: dasetnik
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dasetnik
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: hello
        image: IMAGETOPULL # yourusername/privateimage:version
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: dasetnik
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30100
